Profile page improvements added
bounswe/bounswe2022group3 pull request #412
Opened 2022-12-03 19:04 UTC by arfakbaba

* implemented public profile 
* implemnted private profile 
* implemented edit profile backend connections

2022-12-04 10:12 UTC, nurlandadashov02 requested changes
Good job. But please correct points I made in comments. Thanks.

2022-12-04 10:12 UTC, nurlandadashov02 commented on app/client/pages/user/[user_id].js
> +import { authorization } from '../../../server/src/services/auth';
remove this we should not access backend code in frontend

2022-12-04 10:12 UTC, nurlandadashov02 commented on app/client/pages/user/[user_id].js
> +                      src={personalValues.image}
`${API_URL}/user/${personalValues.image}`. image url should be in this form. Correct this and make sure that profile photo is visible

2022-12-04 10:12 UTC, nurlandadashov02 commented on app/client/pages/user/[user_id].js
> +                        Knowledges
Knowledge

2022-12-04 10:12 UTC, nurlandadashov02 commented on app/client/pages/user/[user_id].js
>                            label="Intrests"
Interests

2022-12-04 10:12 UTC, nurlandadashov02 commented on app/client/pages/user/[user_id].js
>                          <TextField
Knowledge and interests should be tag based components. You can use the code here: https://stackoverflow.com/questions/71585321/create-tag-using-autocomplete-material-ui-when-user-input-anything.   When viewing public profile disable the input

2022-12-04 21:02 UTC, nurlandadashov02 requested changes
You have to make interests and knowledge as tag input in edit mode as well. Update profile backend connection is not working properly. Make sure you are providing correct payload to request. If problem continues, contact backend team.

2022-12-05 17:39 UTC, nurlandadashov02 approved these changes

2022-12-05 17:43 UTC, berkeozdemir2016400246 approved these changes

2022-12-05 17:43 UTC, merged